const translations={
de:{navStory:"STORY",navBand:"BAND",navMusic:"MUSIK",heroEyebrow:"VIRTUAL ALTERNATIVE ROCK · DEUTSCHLAND × TSCHECHIEN",heroLead:"Vier Persönlichkeiten. Ein kompromissloser Sound. Nach Mitternacht beginnt ein neues Kapitel.",heroButton:"MUSIK ENTDECKEN",storyLabel:"DIE GESCHICHTE",storyTitle:"WENN DIE NACHT<br><em>IHRE STIMME FINDET.</em>",storyP1:"Midnight Rebels ist ein deutsch-tschechisches virtuelles Alternative-Rock-Projekt mit starken Stimmen, rauen Gitarren und moderner elektronischer Spannung.",storyP2:"Caroline, Kate, Georg und Jürgen bringen jeweils eine andere Energie mit. Gemeinsam machen sie Musik über Beziehungen, Widerstand, Fehler und den Mut, neu anzufangen.",factMembers:"BANDMITGLIEDER",factSongs:"ORIGINALSONGS",factLanguages:"WEBSPRACHEN",factCountries:"VERBUNDENE LÄNDER",bandLabel:"DIE BAND",roleCaroline:"Leadgesang · Stimme des Projekts",roleKate:"Gitarre · Backing Vocals",roleGeorg:"Bass · Elektronische Elemente",roleJurgen:"Gitarre · Rhythmus",bioCaroline:"Das emotionale Zentrum von Midnight Rebels. Ihre Stimme reicht von verletzlichen Strophen bis zu direkten, kraftvollen Refrains.",bioKate:"Scharfe Gitarrenlinien und eine starke zweite Stimme. Kate bringt Dringlichkeit, Kontrast und unruhige Energie.",bioGeorg:"Das Fundament unter den Songs. Bass und elektronische Ebenen geben dem Projekt Gewicht und eine moderne Kante.",bioJurgen:"Rhythmus, Antrieb und Gitarrentextur. Jürgen verwandelt leise Spannung in Bewegung, sobald sich die Songs öffnen.",soundLabel:"DER SOUND",soundTitle:"DUNKLE ENERGIE.<br>EHRLICHE EMOTION.",soundRockTitle:"ALTERNATIVE ROCK",soundRockText:"Raue Gitarren, fester Bass und live wirkende Drums bilden den körperlichen Kern der Musik.",soundVoicesTitle:"KONTRASTIERENDE STIMMEN",soundVoicesText:"Weibliche und männliche Perspektiven geben den Songs Spannung, Dialog und emotionale Tiefe.",soundThemesTitle:"ECHTE THEMEN",soundThemesText:"Die Texte stellen sich Liebe, Enttäuschung, Selbstachtung, Schweigen und der Entscheidung, wieder aufzustehen.",connectionLabel:"DIE VERBINDUNG",gabinaText:"Gabina brachte RDK260 und Midnight Rebels zusammen. Sie wurde zur Brücke zwischen zwei Projekten, zwei Ländern und einer gemeinsamen musikalischen Energie.",musicLabel:"DIE SONGS",musicTitle:"NEUE MUSIK",musicNote:"Der vollständige Audioplayer wird aktiviert, sobald die finalen MP3-Dateien hinzugefügt sind.",trackRise:"Ein Song über neue Kraft nach dem Moment, in dem alles verloren schien.",trackUnsayable:"Worte, die zu lange unausgesprochen bleiben — intim, zurückhaltend und emotional direkt.",trackWall:"Druck, Distanz und das Gefühl, mit jemandem zu reden, der nicht mehr zuhört.",collabLabel:"EIN GEMEINSAMES KAPITEL",collabText:"Radek und Veronika treffen auf Caroline und Midnight Rebels. Zwei kreative Handschriften, eine Geschichte auf Tschechisch und Deutsch.",rdkButton:"RDK260.CZ BESUCHEN",virtualProject:"VIRTUELLES MUSIKPROJEKT"},
cs:{navStory:"PŘÍBĚH",navBand:"KAPELA",navMusic:"HUDBA",heroEyebrow:"VIRTUÁLNÍ ALTERNATIVNÍ ROCK · NĚMECKO × ČESKO",heroLead:"Čtyři osobnosti. Jeden nekompromisní zvuk. Po půlnoci začíná nová kapitola.",heroButton:"OBJEVIT HUDBU",storyLabel:"PŘÍBĚH",storyTitle:"KDYŽ NOC<br><em>NAJDE SVŮJ HLAS.</em>",storyP1:"Midnight Rebels je německo-český virtuální alternativně-rockový projekt postavený na výrazných hlasech, syrových kytarách a moderním elektronickém napětí.",storyP2:"Caroline, Kate, Georg a Jürgen přinášejí každý jinou energii. Společně tvoří hudbu o vztazích, odporu, chybách a odvaze začít znovu.",factMembers:"ČLENOVÉ KAPELY",factSongs:"ORIGINÁLNÍ SKLADBY",factLanguages:"JAZYKY WEBU",factCountries:"PROPOJENÉ ZEMĚ",bandLabel:"KAPELA",roleCaroline:"Hlavní zpěv · Hlas projektu",roleKate:"Kytara · Doprovodný zpěv",roleGeorg:"Baskytara · Elektronické prvky",roleJurgen:"Kytara · Rytmus",bioCaroline:"Emocionální střed Midnight Rebels. Její hlas přechází od citlivých slok k přímým a silným refrénům.",bioKate:"Ostré kytarové linky a výrazný druhý hlas. Kate přináší naléhavost, kontrast a neklidnou energii.",bioGeorg:"Základ, na kterém skladby stojí. Baskytara a elektronické vrstvy dávají projektu váhu a moderní hranu.",bioJurgen:"Rytmus, tah a kytarová textura. Jürgen mění tiché napětí v pohyb ve chvíli, kdy se skladby naplno otevřou.",soundLabel:"ZVUK",soundTitle:"TEMNÁ ENERGIE.<br>UPŘÍMNÉ EMOCE.",soundRockTitle:"ALTERNATIVNÍ ROCK",soundRockText:"Syrové kytary, pevná baskytara a živě znějící bicí tvoří fyzické jádro hudby.",soundVoicesTitle:"KONTRASTNÍ HLASY",soundVoicesText:"Ženský a mužský pohled dávají skladbám napětí, dialog a emocionální hloubku.",soundThemesTitle:"SKUTEČNÁ TÉMATA",soundThemesText:"Texty se staví čelem k lásce, zklamání, sebeúctě, mlčení a rozhodnutí znovu vstát.",connectionLabel:"PROPOJENÍ",gabinaText:"Gabina propojila RDK260 a Midnight Rebels. Stala se mostem mezi dvěma projekty, dvěma zeměmi a společnou hudební energií.",musicLabel:"SKLADBY",musicTitle:"NOVÁ HUDBA",musicNote:"Kompletní přehrávač aktivujeme po přidání finálních souborů MP3.",trackRise:"Skladba o nalezení síly po okamžiku, kdy se všechno zdálo ztracené.",trackUnsayable:"Slova, která zůstávají příliš dlouho uvnitř — intimní, zdrženlivá a emocionálně přímá skladba.",trackWall:"Tlak, vzdálenost a pocit, že mluvíte s někým, kdo už neposlouchá.",collabLabel:"SPOLEČNÁ KAPITOLA",collabText:"Radek a Veronika se setkávají s Caroline a Midnight Rebels. Dva tvůrčí rukopisy, jeden příběh v češtině a němčině.",rdkButton:"NAVŠTÍVIT RDK260.CZ",virtualProject:"VIRTUÁLNÍ HUDEBNÍ PROJEKT"},
en:{navStory:"STORY",navBand:"BAND",navMusic:"MUSIC",heroEyebrow:"VIRTUAL ALTERNATIVE ROCK · GERMANY × CZECHIA",heroLead:"Four personalities. One uncompromising sound. A new chapter begins after midnight.",heroButton:"DISCOVER THE MUSIC",storyLabel:"THE STORY",storyTitle:"WHEN THE NIGHT<br><em>FINDS ITS VOICE.</em>",storyP1:"Midnight Rebels is a German-Czech virtual alternative-rock project built on strong voices, raw guitars and modern electronic tension.",storyP2:"Caroline, Kate, Georg and Jürgen each bring a different energy. Together they create music about relationships, resistance, mistakes and the courage to begin again.",factMembers:"BAND MEMBERS",factSongs:"ORIGINAL SONGS",factLanguages:"WEBSITE LANGUAGES",factCountries:"CONNECTED COUNTRIES",bandLabel:"THE BAND",roleCaroline:"Lead vocals · Voice of the project",roleKate:"Guitar · Backing vocals",roleGeorg:"Bass · Electronic elements",roleJurgen:"Guitar · Rhythm",bioCaroline:"The emotional centre of Midnight Rebels. Her voice moves from vulnerable verses to direct, powerful choruses.",bioKate:"Sharp guitar lines and a strong second voice. Kate brings urgency, contrast and restless energy.",bioGeorg:"The foundation beneath the songs. Bass and electronic layers give the project its weight and modern edge.",bioJurgen:"Rhythm, drive and guitar texture. Jürgen turns quiet tension into momentum when the songs open up.",soundLabel:"THE SOUND",soundTitle:"DARK ENERGY.<br>HONEST EMOTION.",soundRockTitle:"ALTERNATIVE ROCK",soundRockText:"Raw guitars, firm bass and live-feeling drums form the physical core of the music.",soundVoicesTitle:"CONTRASTING VOICES",soundVoicesText:"Female and male perspectives give the songs tension, dialogue and emotional depth.",soundThemesTitle:"REAL THEMES",soundThemesText:"The lyrics face love, disappointment, self-respect, silence and the decision to stand up again.",connectionLabel:"THE CONNECTION",gabinaText:"Gabina brought RDK260 and Midnight Rebels together. She became the bridge between two projects, two countries and one shared musical energy.",musicLabel:"THE SONGS",musicTitle:"NEW MUSIC",musicNote:"The complete audio player will be activated when the final MP3 files are added.",trackRise:"A song about finding strength after the moment everything seemed lost.",trackUnsayable:"Words that stay inside too long — intimate, restrained and emotionally direct.",trackWall:"Pressure, distance and the feeling of speaking to someone who is no longer listening.",collabLabel:"A SHARED CHAPTER",collabText:"Radek and Veronika meet Caroline and Midnight Rebels. Two creative identities, one story told in Czech and German.",rdkButton:"VISIT RDK260.CZ",virtualProject:"VIRTUAL MUSIC PROJECT"}
};
Object.assign(translations.de,{galleryLabel:"FOTOARCHIV",galleryTitle:"DIE GESCHICHTE IN BILDERN",galleryText:"Originale Motive aus dem ersten Kapitel des Projekts und seiner Verbindung mit RDK260."});
Object.assign(translations.cs,{galleryLabel:"FOTOARCHIV",galleryTitle:"PŘÍBĚH V OBRAZECH",galleryText:"Původní vizuály z první kapitoly projektu a jeho spojení s RDK260."});
Object.assign(translations.en,{galleryLabel:"PHOTO ARCHIVE",galleryTitle:"THE STORY IN PICTURES",galleryText:"Original visuals from the first chapter of the project and its connection with RDK260."});
Object.assign(translations.de,{debutAlbum:"DEBÜTALBUM",releaseDate:"VERÖFFENTLICHUNG · 30. NOVEMBER 2026",releaseLabel:"GEPLANTE VERÖFFENTLICHUNG",releaseValue:"30. NOVEMBER 2026",previewNote:"Höre eine 30-Sekunden-Hörprobe von jedem Song."});
Object.assign(translations.cs,{debutAlbum:"DEBUTOVÉ ALBUM",releaseDate:"VYDÁNÍ · 30. LISTOPADU 2026",releaseLabel:"PLÁNOVANÉ VYDÁNÍ",releaseValue:"30. LISTOPADU 2026",previewNote:"Poslechněte si 30sekundovou ukázku každé skladby."});
Object.assign(translations.en,{debutAlbum:"DEBUT ALBUM",releaseDate:"RELEASE · 30 NOVEMBER 2026",releaseLabel:"PLANNED RELEASE",releaseValue:"30 NOVEMBER 2026",previewNote:"Listen to a 30-second preview of every song."});
Object.assign(translations.de,{previewButton:"30 SEK"});Object.assign(translations.cs,{previewButton:"30 SEK"});Object.assign(translations.en,{previewButton:"30 SEC"});
Object.assign(translations.de,{visitorsLabel:"BESUCHER"});Object.assign(translations.cs,{visitorsLabel:"NÁVŠTĚVY"});Object.assign(translations.en,{visitorsLabel:"VISITORS"});
Object.assign(translations.de,{streamLabel:"STREAMS & VIDEOS",streamTitle:"HÖREN. SEHEN. LIVE.",streamEmpty:"Neue Veröffentlichungen und Streams erscheinen hier."});
Object.assign(translations.cs,{streamLabel:"STREAMY A VIDEA",streamTitle:"POSLOUCHEJ. SLEDUJ. ŽIVĚ.",streamEmpty:"Nová vydání a streamy se objeví zde."});
Object.assign(translations.en,{streamLabel:"STREAMS & VIDEOS",streamTitle:"LISTEN. WATCH. LIVE.",streamEmpty:"New releases and streams will appear here."});
Object.assign(translations.de,{chatLabel:"FAN-NACHRICHTEN",chatTitle:"HINTERLASSE DEINE NACHRICHT.",chatEmpty:"Schreibe die erste Nachricht an Midnight Rebels.",chatFormTitle:"SCHREIBE AN MIDNIGHT REBELS",chatName:"Name",chatCity:"Stadt / Land",chatMessage:"Nachricht",chatSend:"NACHRICHT SENDEN"});
Object.assign(translations.cs,{chatLabel:"ZPRÁVY FANOUŠKŮ",chatTitle:"ZANECH SVOU ZPRÁVU.",chatEmpty:"Napiš první zprávu pro Midnight Rebels.",chatFormTitle:"NAPIŠ MIDNIGHT REBELS",chatName:"Jméno",chatCity:"Město / země",chatMessage:"Zpráva",chatSend:"ODESLAT ZPRÁVU"});
Object.assign(translations.en,{chatLabel:"FAN MESSAGES",chatTitle:"LEAVE YOUR MESSAGE.",chatEmpty:"Be the first to leave a message for Midnight Rebels.",chatFormTitle:"WRITE TO MIDNIGHT REBELS",chatName:"Name",chatCity:"City / country",chatMessage:"Message",chatSend:"SEND MESSAGE"});
Object.assign(translations.de,{newPhotosLabel:"NEUE FOTOS",newPhotosTitle:"VON DER BAND.",newPhotosEmpty:"Neue Fotos erscheinen hier."});
Object.assign(translations.cs,{newPhotosLabel:"NOVÉ FOTOGRAFIE",newPhotosTitle:"OD KAPELY.",newPhotosEmpty:"Nové fotografie se objeví zde."});
Object.assign(translations.en,{newPhotosLabel:"NEW PHOTOS",newPhotosTitle:"FROM THE BAND.",newPhotosEmpty:"New photos will appear here."});
Object.assign(translations.de,{storyP3:"Das Debütalbum RISE FROM THE DARK vereint 19 Originalsongs zu einem zusammenhängenden Kapitel. Kraftvolle Stimmen, markante Gitarren, elektronische Details und Texte über Nähe, Brüche und neue Stärke formen den unverwechselbaren Charakter von Midnight Rebels. Die Veröffentlichung ist für den 30. November 2026 geplant.",collabText:"RDK260 sind Radek, Daniela, Krystyna und Veronika. Gemeinsam mit Gabina und Midnight Rebels verbinden sie tschechische und deutsche Kreativität in einer Geschichte — mit eigener Identität, eigener Sprache und gemeinsamer Energie."});
Object.assign(translations.cs,{storyP3:"Debutové album RISE FROM THE DARK spojuje 19 původních skladeb do jedné ucelené kapitoly. Výrazné hlasy, silné kytary, elektronické detaily a texty o blízkosti, zlomových okamžicích a nové síle vytvářejí nezaměnitelný charakter Midnight Rebels. Vydání je plánováno na 30. listopadu 2026.",collabText:"RDK260 tvoří Radek, Daniela, Krystyna a Veronika. Společně s Gabinou a Midnight Rebels propojují českou a německou tvorbu v jednom příběhu — s vlastní identitou, vlastním jazykem a společnou energií."});
Object.assign(translations.en,{storyP3:"The debut album RISE FROM THE DARK brings 19 original songs together as one complete chapter. Powerful voices, distinctive guitars, electronic detail and lyrics about connection, breaking points and renewed strength define the unmistakable character of Midnight Rebels. Release is planned for 30 November 2026.",collabText:"RDK260 are Radek, Daniela, Krystyna and Veronika. Together with Gabina and Midnight Rebels, they connect Czech and German creativity in one story — each with its own identity and language, united by a shared energy."});
Object.assign(translations.de,{track01:"WER BLEIBT?",track02:"AUSREDEN VORBEI",track03:"DU SOLLTEST MEINER SEIN — LIVE",track04:"DU SOLLTEST MEINER SEIN",track05:"FRAG MICH NICHT WARUM",track06:"HINTER DEM HORIZONT",track07:"ICH ÄNDERE ALLES",track08:"ICH GEBE NIEMALS AUF",track09:"ICH STEHE WIEDER AUF",track10:"IST MIR EGAL",track11:"JUNGS LÜGEN",track12:"JUNGS, JUNGS",track13:"LASS DAS LICHT AUS",track14:"LEERE WAND",track15:"LIEBE VERKEHRT",track16:"MEIN KOPF SPIELT MIT MIR",track17:"NEBEN DIR SCHWEIGEN — LIVE",track18:"NENN MICH NICHT BABY!",track19:"WAS ICH DIR NICHT SAGEN KANN"});
Object.assign(translations.cs,{track01:"KDO ZŮSTANE?",track02:"KONEC VÝMLUVÁM",track03:"MĚL JSI BÝT MŮJ — ŽIVĚ",track04:"MĚL JSI BÝT MŮJ",track05:"NEPTEJ SE MĚ PROČ",track06:"ZA HORIZONTEM",track07:"ZMĚNÍM VŠECHNO",track08:"NIKDY SE NEVZDÁM",track09:"ZNOVU VSTÁVÁM",track10:"JE MI TO JEDNO",track11:"KLUCI LŽOU",track12:"KLUCI, KLUCI",track13:"ZHASNI SVĚTLO",track14:"PRÁZDNÁ ZEĎ",track15:"OBRÁCENÁ LÁSKA",track16:"MOJE HLAVA SI SE MNOU HRAJE",track17:"MLČET VEDLE TEBE — ŽIVĚ",track18:"NEŘÍKEJ MI BABY!",track19:"CO TI NEDOKÁŽU ŘÍCT"});
Object.assign(translations.en,{track01:"WHO STAYS?",track02:"NO MORE EXCUSES",track03:"YOU SHOULD HAVE BEEN MINE — LIVE",track04:"YOU SHOULD HAVE BEEN MINE",track05:"DON'T ASK ME WHY",track06:"BEYOND THE HORIZON",track07:"I CHANGE EVERYTHING",track08:"I NEVER GIVE UP",track09:"I RISE AGAIN",track10:"I DON'T CARE",track11:"BOYS LIE",track12:"BOYS, BOYS",track13:"TURN OFF THE LIGHT",track14:"EMPTY WALL",track15:"LOVE GONE WRONG",track16:"MY MIND PLAYS WITH ME",track17:"SILENT BESIDE YOU — LIVE",track18:"DON'T CALL ME BABY!",track19:"WHAT I CAN'T TELL YOU"});
function setLanguage(lang){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=translations[lang][el.dataset.i18n];if(value)el.innerHTML=value});document.querySelectorAll("[data-lang]").forEach(button=>button.classList.toggle("active",button.dataset.lang===lang));localStorage.setItem("midnight-rebels-language",lang);updateGiscusLanguage(lang)}
function updateGiscusLanguage(lang){const frame=document.querySelector("iframe.giscus-frame");if(frame)frame.contentWindow.postMessage({giscus:{setConfig:{lang}}},"https://giscus.app")}
document.querySelectorAll("[data-lang]").forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.lang)));
const menu=document.querySelector(".menu-button"),nav=document.querySelector("nav");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)});nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>nav.classList.remove("open")));
const lightbox=document.querySelector(".lightbox"),lightboxImage=lightbox.querySelector("img");document.querySelectorAll(".gallery-grid button").forEach(button=>button.addEventListener("click",()=>{lightboxImage.src=button.dataset.full;lightboxImage.alt=button.querySelector("img").alt;lightbox.showModal()}));lightbox.querySelector(".lightbox-close").addEventListener("click",()=>lightbox.close());lightbox.addEventListener("click",event=>{if(event.target===lightbox)lightbox.close()});
const previewAudio=new Audio();previewAudio.preload="none";let activePreview=null;function resetPreview(){if(activePreview){activePreview.classList.remove("playing");activePreview.querySelector(":scope > span").textContent="▶"}activePreview=null}document.querySelectorAll(".preview").forEach(button=>button.addEventListener("click",()=>{if(activePreview===button&&!previewAudio.paused){previewAudio.pause();resetPreview();return}resetPreview();activePreview=button;previewAudio.src=button.dataset.audio;previewAudio.currentTime=0;button.classList.add("playing");button.querySelector(":scope > span").textContent="■";previewAudio.play().catch(resetPreview)}));previewAudio.addEventListener("ended",resetPreview);previewAudio.addEventListener("error",resetPreview);
setLanguage(localStorage.getItem("midnight-rebels-language")||"de");
const visitorCount=document.getElementById("visitor-count");
const isLocalFile=location.protocol==="file:";
if(visitorCount&&isLocalFile){
  visitorCount.textContent="—";
}else if(visitorCount&&typeof Counter!=="undefined"){
  const siteCounter=new Counter({workspace:"midnight-rebels-radek8491-prog",timeout:5000});
  siteCounter.up("page-views").then(result=>{visitorCount.textContent=Number(result.value).toLocaleString()}).catch(()=>{visitorCount.textContent="—"});
}

const mediaRoot=document.getElementById("dynamic-media"),mediaAdmin=document.getElementById("media-admin"),mediaForm=document.getElementById("media-form"),adminTrigger=document.getElementById("secret-admin-trigger"),mediaAdminClose=document.getElementById("media-admin-close");
const mediaConfig={owner:"radek8491-prog",repo:"midnight-rebels",path:"media-links.json",branch:"main"};
let mediaItems=[],adminUnlocked=false,secretClicks=0,secretTimer;
function youtubeId(value){try{const url=new URL(value),host=url.hostname.replace(/^www\./,"");if(host==="youtu.be")return url.pathname.split("/").filter(Boolean)[0]||"";if(host.endsWith("youtube.com")){if(url.pathname==="/watch")return url.searchParams.get("v")||"";const parts=url.pathname.split("/").filter(Boolean);if(["live","shorts","embed"].includes(parts[0]))return parts[1]||""}}catch{}return""}
function renderMedia(){if(!mediaRoot)return;mediaRoot.replaceChildren();if(!mediaItems.length){const empty=document.createElement("p");empty.className="media-empty";empty.dataset.i18n="streamEmpty";empty.textContent=translations[document.documentElement.lang]?.streamEmpty||translations.de.streamEmpty;mediaRoot.append(empty);return}mediaItems.forEach((item,index)=>{const card=document.createElement("article");card.className="stream-card";const id=youtubeId(item.url);if(id){const frame=document.createElement("iframe");frame.src="https://www.youtube.com/embed/"+encodeURIComponent(id)+"?playsinline=1&rel=0";frame.title=item.title||"Midnight Rebels YouTube";frame.loading="lazy";frame.allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share";frame.allowFullscreen=true;card.append(frame)}else{const link=document.createElement("a");link.className="stream-external";link.href=item.url;link.target="_blank";link.rel="noopener noreferrer";link.innerHTML="<span>▶</span><strong></strong><small>AMUSE · STREAM</small>";link.querySelector("strong").textContent=item.title||"Midnight Rebels";card.append(link)}const heading=document.createElement("h3");heading.textContent=item.title||"Midnight Rebels";card.append(heading);if(adminUnlocked){const remove=document.createElement("button");remove.type="button";remove.className="media-delete";remove.textContent="VYMAZAT";remove.addEventListener("click",()=>removeMedia(index));card.append(remove)}mediaRoot.append(card)})}
async function loadMedia(){if(isLocalFile){mediaItems=[];renderMedia();return}try{const response=await fetch(mediaConfig.path+"?v="+Date.now(),{cache:"no-store"});if(!response.ok)throw Error();const value=await response.json();mediaItems=Array.isArray(value)?value:[];renderMedia()}catch{mediaItems=[];renderMedia()}}
async function saveMedia(nextItems){const token=document.getElementById("github-token").value.trim()||sessionStorage.getItem("midnightRebelsGithubToken")||"";if(!token)throw Error("Vlož GitHub token.");sessionStorage.setItem("midnightRebelsGithubToken",token);const api="https://api.github.com/repos/"+mediaConfig.owner+"/"+mediaConfig.repo+"/contents/"+mediaConfig.path;const headers={Accept:"application/vnd.github+json",Authorization:"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28"};const current=await fetch(api+"?ref="+mediaConfig.branch,{headers});if(!current.ok)throw Error("GitHub nepovolil načtení souboru.");const info=await current.json(),content=btoa(unescape(encodeURIComponent(JSON.stringify(nextItems,null,2)+"\n")));const saved=await fetch(api,{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({message:"Update Midnight Rebels stream links",content,sha:info.sha,branch:mediaConfig.branch})});if(!saved.ok)throw Error("GitHub nepovolil uložení. Zkontroluj oprávnění tokenu.");mediaItems=nextItems;renderMedia()}
async function removeMedia(index){if(!confirm("Vymazat tento odkaz z webu?"))return;const status=document.getElementById("media-admin-status"),token=document.getElementById("github-token").value.trim()||sessionStorage.getItem("midnightRebelsGithubToken")||"",nextItems=mediaItems.filter((_,itemIndex)=>itemIndex!==index);try{if(!token){mediaItems=nextItems;renderMedia();status.textContent="Zkušební odkaz byl vymazán.";return}status.textContent="Mažu…";await saveMedia(nextItems);status.textContent="Odkaz byl vymazán."}catch(error){status.textContent=error.message}}
if(adminTrigger){adminTrigger.addEventListener("click",()=>{secretClicks++;clearTimeout(secretTimer);secretTimer=setTimeout(()=>secretClicks=0,1200);if(secretClicks<3)return;secretClicks=0;clearTimeout(secretTimer);const password=prompt("Pokračovat:");if(password===String.fromCharCode(76,111,118,101,49,50,51)){adminUnlocked=true;mediaAdmin.hidden=false;photoAdmin.hidden=false;renderMedia();renderUploadedPhotos();mediaAdmin.scrollIntoView({behavior:"smooth",block:"center"})}else if(password!==null)alert("Nesprávné heslo.")})}
if(mediaAdminClose){mediaAdminClose.addEventListener("click",()=>{mediaAdmin.hidden=true;photoAdmin.hidden=true;renderMedia();renderUploadedPhotos();renderFanMessages()})}
if(mediaForm){mediaForm.addEventListener("submit",async event=>{event.preventDefault();const title=document.getElementById("media-title").value.trim(),url=document.getElementById("media-url").value.trim(),status=document.getElementById("media-admin-status"),token=document.getElementById("github-token").value.trim()||sessionStorage.getItem("midnightRebelsGithubToken")||"";try{new URL(url);const item={title,url,createdAt:new Date().toISOString()};if(!token){mediaItems=[item,...mediaItems];renderMedia();document.getElementById("media-title").value="";document.getElementById("media-url").value="";status.textContent="ZKUŠEBNÍ NÁHLED — odkaz není zveřejněný a po obnovení stránky zmizí.";mediaRoot.scrollIntoView({behavior:"smooth",block:"start"});return}status.textContent="Ukládám…";await saveMedia([item,...mediaItems]);mediaForm.reset();status.textContent="Odkaz byl zveřejněn."}catch(error){status.textContent=error.message}})}
loadMedia();

const uploadedPhotoGrid=document.getElementById("uploaded-photo-grid"),photoAdmin=document.getElementById("photo-admin"),photoAdminClose=document.getElementById("photo-admin-close"),photoUploadForm=document.getElementById("photo-upload-form"),photoManifestPath="uploaded-photos.json";
let uploadedPhotos=[];
function renderUploadedPhotos(){if(!uploadedPhotoGrid)return;uploadedPhotoGrid.replaceChildren();if(!uploadedPhotos.length){const empty=document.createElement("p");empty.className="media-empty";empty.dataset.i18n="newPhotosEmpty";empty.textContent=translations[document.documentElement.lang]?.newPhotosEmpty||translations.de.newPhotosEmpty;uploadedPhotoGrid.append(empty);return}uploadedPhotos.forEach((photo,index)=>{const figure=document.createElement("figure");figure.className="uploaded-photo";const image=document.createElement("img");image.src=photo.url;image.alt=photo.caption||"Midnight Rebels";image.loading="lazy";figure.append(image);if(photo.caption){const caption=document.createElement("figcaption");caption.textContent=photo.caption;figure.append(caption)}if(adminUnlocked){const remove=document.createElement("button");remove.type="button";remove.textContent="VYMAZAT";remove.addEventListener("click",()=>deleteUploadedPhoto(index));figure.append(remove)}uploadedPhotoGrid.append(figure)})}
async function loadUploadedPhotos(){if(isLocalFile){uploadedPhotos=[];renderUploadedPhotos();return}try{const response=await fetch(photoManifestPath+"?v="+Date.now(),{cache:"no-store"});if(!response.ok)throw Error();const value=await response.json();uploadedPhotos=Array.isArray(value)?value:[]}catch{uploadedPhotos=[]}renderUploadedPhotos()}
function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
function githubHeaders(token,json=false){return{Accept:"application/vnd.github+json",Authorization:"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28",...(json?{"Content-Type":"application/json"}:{})}}
async function githubJsonUpdate(path,value,token,message){const api="https://api.github.com/repos/"+mediaConfig.owner+"/"+mediaConfig.repo+"/contents/"+path,current=await fetch(api+"?ref="+mediaConfig.branch,{headers:githubHeaders(token)});if(!current.ok)throw Error("GitHub nepovolil načtení dat.");const info=await current.json(),content=btoa(unescape(encodeURIComponent(JSON.stringify(value,null,2)+"\n"))),response=await fetch(api,{method:"PUT",headers:githubHeaders(token,true),body:JSON.stringify({message,content,sha:info.sha,branch:mediaConfig.branch})});if(!response.ok)throw Error("GitHub nepovolil uložení dat.")}
async function uploadPhotoFile(file,token){const safeName=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"-").toLowerCase(),path="assets/uploads/"+Date.now()+"-"+safeName,api="https://api.github.com/repos/"+mediaConfig.owner+"/"+mediaConfig.repo+"/contents/"+path,content=await fileToBase64(file),response=await fetch(api,{method:"PUT",headers:githubHeaders(token,true),body:JSON.stringify({message:"Upload Midnight Rebels photo",content,branch:mediaConfig.branch})});if(!response.ok)throw Error("Fotografii se nepodařilo nahrát.");return path}
async function deleteUploadedPhoto(index){if(!confirm("Vymazat tuto fotografii?"))return;const status=document.getElementById("photo-upload-status"),token=document.getElementById("photo-github-token").value.trim()||sessionStorage.getItem("midnightRebelsGithubToken")||"",photo=uploadedPhotos[index],next=uploadedPhotos.filter((_,itemIndex)=>itemIndex!==index);try{if(!token||photo.local){if(photo.local)URL.revokeObjectURL(photo.url);uploadedPhotos=next;renderUploadedPhotos();status.textContent="Zkušební fotografie byla vymazána.";return}const api="https://api.github.com/repos/"+mediaConfig.owner+"/"+mediaConfig.repo+"/contents/"+photo.path,current=await fetch(api+"?ref="+mediaConfig.branch,{headers:githubHeaders(token)});if(!current.ok)throw Error("Soubor fotografie nebyl nalezen.");const info=await current.json(),removed=await fetch(api,{method:"DELETE",headers:githubHeaders(token,true),body:JSON.stringify({message:"Delete Midnight Rebels photo",sha:info.sha,branch:mediaConfig.branch})});if(!removed.ok)throw Error("Fotografii se nepodařilo vymazat.");await githubJsonUpdate(photoManifestPath,next,token,"Update Midnight Rebels photo gallery");uploadedPhotos=next;renderUploadedPhotos();status.textContent="Fotografie byla vymazána."}catch(error){status.textContent=error.message}}
if(photoAdminClose){photoAdminClose.addEventListener("click",()=>{photoAdmin.hidden=true})}
if(photoUploadForm){photoUploadForm.addEventListener("submit",async event=>{event.preventDefault();const file=document.getElementById("photo-file").files[0],caption=document.getElementById("photo-caption").value.trim(),token=document.getElementById("photo-github-token").value.trim()||sessionStorage.getItem("midnightRebelsGithubToken")||"",status=document.getElementById("photo-upload-status");if(!file)return;if(file.size>8*1024*1024){status.textContent="Fotografie je větší než 8 MB.";return}try{if(!token){uploadedPhotos=[{url:URL.createObjectURL(file),caption,local:true},...uploadedPhotos];renderUploadedPhotos();photoUploadForm.reset();status.textContent="ZKUŠEBNÍ NÁHLED — fotografie po obnovení stránky zmizí.";return}sessionStorage.setItem("midnightRebelsGithubToken",token);status.textContent="Nahrávám…";const path=await uploadPhotoFile(file,token),next=[{url:path,path,caption,createdAt:new Date().toISOString()},...uploadedPhotos];await githubJsonUpdate(photoManifestPath,next,token,"Update Midnight Rebels photo gallery");uploadedPhotos=next;renderUploadedPhotos();photoUploadForm.reset();status.textContent="Fotografie byla zveřejněna."}catch(error){status.textContent=error.message}})}
loadUploadedPhotos();

const fanMessages=document.getElementById("fan-messages"),fanChatForm=document.getElementById("fan-chat-form"),fanChatStorage="midnightRebelsTestMessages";
function readFanMessages(){try{const value=JSON.parse(localStorage.getItem(fanChatStorage)||"[]");if(!Array.isArray(value))return[];let changed=false;value.forEach((item,index)=>{if(!item.id){item.id="message-"+String(item.createdAt||Date.now())+"-"+index;changed=true}if(!Array.isArray(item.replies)){item.replies=[];changed=true}});if(changed)localStorage.setItem(fanChatStorage,JSON.stringify(value));return value}catch{return[]}}
function saveFanMessages(items){localStorage.setItem(fanChatStorage,JSON.stringify(items.slice(-50)));renderFanMessages()}
function canDeleteFanMessages(){return adminUnlocked||location.protocol==="file:"}
function deleteFanMessage(id){if(!canDeleteFanMessages()||!confirm("Vymazat tuto zprávu a všechny její reakce?"))return;saveFanMessages(readFanMessages().filter(item=>item.id!==id))}
function deleteFanReply(messageId,replyId){if(!canDeleteFanMessages()||!confirm("Vymazat tuto reakci?"))return;const items=readFanMessages();const parent=items.find(item=>item.id===messageId);if(parent)parent.replies=(parent.replies||[]).filter(reply=>reply.id!==replyId);saveFanMessages(items)}
function openReplyForm(article,item){article.querySelector(".inline-reply-form")?.remove();const form=document.createElement("form");form.className="inline-reply-form";const official=adminUnlocked;form.innerHTML='<strong>'+(official?'MIDNIGHT REBELS · OFFICIAL':'ODPOVĚĎ')+'</strong><label>Jméno<input class="reply-name" maxlength="60" required></label><label>Zpráva<textarea class="reply-message" maxlength="800" required></textarea></label><div><button class="reply-submit" type="submit">ODESLAT ODPOVĚĎ</button><button class="reply-cancel" type="button">ZRUŠIT</button></div>';const nameInput=form.querySelector(".reply-name");if(official){nameInput.value="MIDNIGHT REBELS · OFFICIAL";nameInput.readOnly=true}form.querySelector(".reply-cancel").addEventListener("click",()=>form.remove());form.addEventListener("submit",event=>{event.preventDefault();const items=readFanMessages(),parent=items.find(message=>message.id===item.id);if(!parent)return;parent.replies=Array.isArray(parent.replies)?parent.replies:[];parent.replies.push({id:crypto.randomUUID?.()||String(Date.now()),name:nameInput.value.trim(),message:form.querySelector(".reply-message").value.trim(),official,createdAt:new Date().toISOString()});saveFanMessages(items)});article.append(form);form.querySelector(".reply-message").focus()}
function renderFanMessages(){if(!fanMessages)return;const items=readFanMessages();fanMessages.replaceChildren();if(!items.length){const empty=document.createElement("p");empty.className="chat-empty";empty.dataset.i18n="chatEmpty";empty.textContent=translations[document.documentElement.lang]?.chatEmpty||translations.de.chatEmpty;fanMessages.append(empty);return}items.slice().reverse().forEach(item=>{if(!item.id)item.id=String(item.createdAt||Date.now());const article=document.createElement("article");article.className="fan-message-item";const head=document.createElement("div");head.className="fan-message-head";const name=document.createElement("strong");name.textContent=item.name;const meta=document.createElement("span");meta.textContent=[item.city,new Date(item.createdAt).toLocaleString()].filter(Boolean).join(" · ");const message=document.createElement("p");message.textContent=item.message;const actions=document.createElement("div");actions.className="fan-message-actions";const replyButton=document.createElement("button");replyButton.type="button";replyButton.textContent=adminUnlocked?"ODPOVĚDĚT JAKO KAPELA":"ODPOVĚDĚT";replyButton.addEventListener("click",()=>openReplyForm(article,item));actions.append(replyButton);if(canDeleteFanMessages()){const remove=document.createElement("button");remove.type="button";remove.textContent="VYMAZAT";remove.addEventListener("click",()=>deleteFanMessage(item.id));actions.append(remove)}head.append(name,meta);article.append(head,message,actions);const thread=document.createElement("div");thread.className="reply-thread";(item.replies||[]).forEach(reply=>{const replyBox=document.createElement("article");replyBox.className="fan-reply"+(reply.official?" official":"");const replyHead=document.createElement("div");replyHead.className="fan-message-head";const replyName=document.createElement("strong");replyName.textContent=reply.name;const replyTime=document.createElement("span");replyTime.textContent=new Date(reply.createdAt).toLocaleString();const replyText=document.createElement("p");replyText.textContent=reply.message;replyHead.append(replyName,replyTime);replyBox.append(replyHead,replyText);if(canDeleteFanMessages()){const removeReply=document.createElement("button");removeReply.type="button";removeReply.className="reply-delete";removeReply.textContent="VYMAZAT REAKCI";removeReply.addEventListener("click",()=>deleteFanReply(item.id,reply.id));replyBox.append(removeReply)}thread.append(replyBox)});article.append(thread);fanMessages.append(article)})}
if(fanChatForm){fanChatForm.addEventListener("submit",event=>{event.preventDefault();const items=readFanMessages(),name=document.getElementById("fan-name").value.trim(),city=document.getElementById("fan-city").value.trim(),message=document.getElementById("fan-message").value.trim(),status=document.getElementById("fan-chat-status");items.push({id:crypto.randomUUID?.()||String(Date.now()),name,city,message,createdAt:new Date().toISOString(),replies:[]});saveFanMessages(items);fanChatForm.reset();status.textContent="ZKUŠEBNÍ ZPRÁVA — je uložená pouze v tomto prohlížeči."})}
renderFanMessages();
function initPublicFanChat(){const root=document.querySelector(".giscus"),note=document.querySelector(".giscus-local-note");if(!root)return;if(location.protocol==="file:"){if(note)note.hidden=false;return}const script=document.createElement("script");script.src="https://giscus.app/client.js";Object.entries({repo:"radek8491-prog/midnight-rebels","repo-id":"R_kgDOUYz_Hw",category:"Announcements","category-id":"DIC_kwDOUYz_H84DFf62",mapping:"specific",term:"MIDNIGHT REBELS — ZPRÁVY FANOUŠKŮ · FAN MESSAGES",strict:"1","reactions-enabled":"1","emit-metadata":"0","input-position":"top",theme:"dark_dimmed",lang:document.documentElement.lang}).forEach(([key,value])=>script.setAttribute("data-"+key,value));script.crossOrigin="anonymous";script.async=true;root.append(script)}
initPublicFanChat();
